server:
  port: 8085
spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8180/realms/laptrinhfullstack
  data:
    redis:
      port: 6379
      host: redis
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employeeservice
          uri: lb://employeeservice
          predicates:
            - Path=/api/v1/employees/**
          filters:
            - JwtHeaderFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
            - KeyAuthFilter
        - id: bookservice
          uri: lb://bookservice
          predicates:
            - Path=/api/v1/books/**
          filters:
            - JwtHeaderFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
            - KeyAuthFilter
        - id: userservice
          uri: http://host.docker.internal:9004
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: JwtHeaderFilter

        - id: userservice-public
          uri: http://host.docker.internal:9004
          predicates:
            - Path=/api/v1/public/**
eureka:
  instance:
    hostname: discoveryservice
  client:
    service-url:
      defaultZone: http://discoveryservice:8761/eureka
    register-with-eureka: true
    fetch-registry: true


